### ISSUE TITLE
Add an RSS feed

### ISSUE THREAD

**Issue by joech4n** [virtuallyhyper/virtuallyhyper.github.io#26]
Per @Mstaaravin's [tweet](https://twitter.com/Mstaaravin/status/562330706899394560), we should do this! :)

We can probably just follow [this guide](http://joelglovier.com/writing/rss-for-jekyll/).

**Comment by joech4n** [comment]
Looks like we have some templates already at:
* http://virtuallyhyper.com/atom.xml
* http://virtuallyhyper.com/rss.xml

Maybe we just need to change the filenames...

**Comment by Mstaaravin** [comment]
No, is a parsing error...
![](http://s5.postimg.org/ihdttavvr/Selection_026.png)

**Comment by joech4n** [comment]
Can you check if it works now @Mstaaravin ?

**Comment by Mstaaravin** [comment]
works fine now!

**Comment by moopless** [comment]
Thanks for taking care of this @joech4n
